# Generates defaults_local.go with the YouTube OAuth client id/secret so the
# creds are baked into the sidecar build and users connect a channel in one
# click. Sources, in priority order: -ClientId/-ClientSecret parameters, then
# the local Flapp settings (%APPDATA%\flapp\settings.json).
# The file is gitignored — re-run after a fresh clone. Run from repo root:
#   powershell -ExecutionPolicy Bypass -File scripts\gen-yt-defaults.ps1
#   powershell -ExecutionPolicy Bypass -File scripts\gen-yt-defaults.ps1 -ClientId "..." -ClientSecret "..."
param(
    [string]$ClientId = "",
    [string]$ClientSecret = ""
)

$ErrorActionPreference = "Stop"

if (-not $ClientId -or -not $ClientSecret) {
    $settingsPath = Join-Path $env:APPDATA "flapp\settings.json"
    if (Test-Path $settingsPath) {
        $j = Get-Content $settingsPath -Raw | ConvertFrom-Json
        if (-not $ClientId) { $ClientId = $j.ytClientId }
        if (-not $ClientSecret) { $ClientSecret = $j.ytClientSecret }
    }
}
if (-not $ClientId -or -not $ClientSecret) {
    Write-Error "No creds: pass -ClientId/-ClientSecret or enter them in Flapp settings first (Google Cloud Console -> Credentials -> your Desktop app client)."
}

$out = Join-Path $PSScriptRoot "..\backend\internal\infrastructure\youtube\defaults_local.go"
$src = @"
package youtube

// Code generated by scripts/gen-yt-defaults.ps1 from local settings.json.
// DO NOT COMMIT (gitignored).

func init() {
	DefaultClientID = "$ClientId"
	DefaultClientSecret = "$ClientSecret"
}
"@

# UTF-8 without BOM — Go tooling chokes on a BOM in source files.
[System.IO.File]::WriteAllText((Resolve-Path (Split-Path $out) | Join-Path -ChildPath (Split-Path $out -Leaf)), $src, (New-Object System.Text.UTF8Encoding $false))
Write-Host "OK: defaults_local.go generated (client id $($ClientId.Substring(0, [Math]::Min(12, $ClientId.Length)))...)"
